##############################################################################
#                              Runtimes Overlay                              #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#          https://kometa.wiki/en/latest/defaults/overlays/runtimes          #
##############################################################################

external_templates:
  default: templates
  template_variables:
    default:
      text: ""
      horizontal_align: left
      vertical_align: top
    conditionals:
      vertical_offset:
        default: 15
        conditions:
          - vertical_align: center
            value: 0
          - vertical_align: top
            value: 15
          - vertical_align: top
            value: 30
      horizontal_offset:
        default: 15
        conditions:
          - horizontal_align: center
            value: 0
          - horizontal_align: [left, right]
            value: 355
    back_color: "#00000099"
    back_width: 400
    back_height: 105
    final_name: "text(total: <<total_runtime_unseenH>>h <<total_runtime_unseenM>>m)"

overlays:
  runtime_info:
    plex_all: true
    template:
      name: standard
